version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/src
    networks:
      - appnet

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - react_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_HOST=api
      - NEXT_PUBLIC_API_PORT=5000
    depends_on:
      - api
    networks:
      - appnet

  webapp-angular:
    build:
      context: ./webapp-angular
      dockerfile: Dockerfile
    container_name: webapp-angular
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - appnet
    volumes:
      - ./webapp-angular:/app
      - angular_node_modules:/app/node_modules


networks:
  appnet:

volumes:
  react_node_modules:
  angular_node_modules:

